# Generated by Django 4.0.5 on 2022-07-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
