# Generated by Django 4.0.5 on 2022-07-28 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profile_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stars',
        ),
        migrations.AddField(
            model_name='profile',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='user_start', to=settings.AUTH_USER_MODEL),
        ),
    ]
