# Generated by Django 4.0.5 on 2022-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_stars_profile_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stars_count',
            field=models.IntegerField(default=0),
        ),
    ]
