# Generated by Django 4.0.5 on 2022-07-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_stars_profile_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follower',
            new_name='stars',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vote',
        ),
    ]
