# Generated by Django 4.0.5 on 2022-07-30 06:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('myapp', '0004_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='taglarni vergul(,) bilan ajratib yozing!', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
