# Generated by Django 4.0.5 on 2022-07-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_post_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
